# -*- coding: utf-8 -*-
"""Project Tetris Batch 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SL_ixm1YkcS34Bfl6PT0Gkv5kzbGbkm

#Persebaran Covid-19 Di Dunia dan Asia Tenggara

Sejak dimulainya pandemi COVID-19 pada tahun 2020, dunia telah mengalami tantangan besar dalam menghadapi penyebaran virus yang mematikan ini. Pada awal 2020, banyak negara menghadapi gelombang pertama kasus COVID-19. Oleh karena itu, diperlukan peta persebaran kasus Covid-19 didunia. Data diambil dari website Kaggle yang bersumber WorldOmeter. Untuk linknya sebagai berikut : https://www.kaggle.com/datasets/themrityunjaypathak/covid-cases-and-deaths-worldwide

# Mengambil data dari Google Drive
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/drive')
# %cd /drive

"""#Instal Library"""

! pip install lifelines
! pip install lifetimes
! pip install kneed
! pip install squarify

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import matplotlib.ticker as mtick
# %matplotlib inline
import seaborn as sns
sns.set()
import ast
import json
from scipy import stats
from datetime import datetime, date
import datetime as dt
import random
import os
import re
import sys
import timeit
import string
import time
from time import time
from dateutil.parser import parse
import joblib
import math
import lifelines
import squarify

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

"""#Import Data Dari Google Drive

Untuk link Google Drive nya : https://drive.google.com/file/d/1MOffTxAdEmmW1KEYN9dFxm7QRhG6w06z/view?usp=sharing
"""

#import dataset
covid_data = pd.read_csv("MyDrive/covid_worldwide.csv")

"""#Data Cleansing"""

covid_data

#Mengetahui tipe data
covid_data.info()

#Mengetahui nilai null
covid_data.isnull().sum()

#Mengubah nilai null menjadi nilai 0
covid_data.fillna(0, inplace=True)

#Mengubah tipe data ke integer
covid_data['Total Cases']= covid_data['Total Cases'].astype(int)
covid_data['Total Deaths']= covid_data['Total Deaths'].astype(int)
covid_data['Total Recovered']= covid_data['Total Recovered'].astype(int)
covid_data['Active Cases']= covid_data['Active Cases'].astype(int)
covid_data['Total Test']= covid_data['Total Test'].astype(int)
covid_data['Population']= covid_data['Population'].astype(int)

#Mengubah tipe data ke string
covid_data['Country']= covid_data['Country'].astype('string')

print(covid_data.info())

"""#Exploratory Data Analysis (EDA)"""

covid_data

# Mengurutkan Data berdasarkan 'Total Cases' secara descending
covid_data_sorted = covid_data.sort_values(by='Total Cases', ascending=False)

# Mengambil top 5 negara teratas
top5_countries = covid_data_sorted.head(5)
top5_countries

# Menghitung jumlah kasus COVID-19
total_cases = covid_data['Total Cases'].sum()
total_cases

"""#Mengexport Ke File CSV"""

cd ~

from google.colab import files
covid_data.to_csv('covid_data.csv', index=False)
files.download('covid_data.csv')